/*
 * LazyWrite - deferred document.write implementation
 * Version: 1.0 beta build 20110212
 * Website: http://github.com/xfsn/LazyWrite
 * 
 * Copyright (c) 2011 Shen Junru
 * Released under the MIT License.
 */
(function(v,h){var C=1,g=!-[1,],x=g?"onreadystatechange":"onload",l=v.write,w=v.writeln,b=v.createDocumentFragment(),s=v.createElement("div"),y=h,r=h,i=h,j=h,e=[],f=[],q=false,c=true,k=[].join,D=function(G,F){return G.appendChild(F)},o=function(F){return F.parentNode?F.parentNode.removeChild(F):F},a=function(G,F){return G.parentNode.replaceChild(F,G)&&F},u=function(){return v.createElement("span")},B=function m(G){var F=v.createElement("script");F.type=G.type;if(G.src){F.src=G.src}else{F.text=G.text}return F},A=function(G,F){if(F.src){F[x]=function(){var H=g&&F.readyState;if(!F.done&&(!H||/complete|loaded/.test(H))){if(H==="loaded"&&!F.loaded){F.loaded=true;setTimeout(arguments.callee)}else{F.done=true;F[x]=null;o(G);if(r===F){r=h;d()}}}};r=F;setTimeout(function(){D(G,F)})}else{F.text="try{"+F.text+"}catch(_ex_){}";D(G,F);o(G)}},t=function(F){if(F){if(!r){y=F.holder}A(F.holder,F.script=B(F.script));return !F.script.src}},z=function(F){while((F=t(f.shift()))){}return F!==false&&!r},p=function(I,J,H){if(g){s.innerHTML="<img />"+J;o(s.firstChild)}else{s.innerHTML=J}var G=[],F=s.getElementsByTagName("script");while(F[0]){G.push({script:F[0],holder:a(F[0],element=u())})}f=G.concat(f);while(s.firstChild){b.appendChild(s.firstChild)}if(i===I){j.parentNode.insertBefore(b,j)}else{j=b.appendChild(j||u());H?I.parentNode.insertBefore(b,I.nextSibling):a(I,b)}i=I;if(G.length){c=z()}return c},E=function(F){return F&&p(v.getElementById(F.id),F.html)},n=function(F){while(E(e.shift())){}if(c&&!e.length){j&&o(j);b=s=y=r=i=j=h;v.write=l;v.writeln=w}},d=function(){c=true;if(z()){n()}};v.writeln=v.write=function(){var G,F=k.call(arguments,"");if(q){try{p(y,F,true)}catch(H){}}else{e.push({id:G="document_write_"+C++,html:F});G='<span id="'+G+'"></span>';l.call?l.call(v,G):l(G)}};window.LazyWrite={write:function(){l.apply(v,arguments)},start:function(){if(q){return}q=true;n()}}})(document);
